version: "3.5"

services:
  web:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    # networks:
    #   - main
    # depends_on:
    #   - db
  # app:
  #   build:
  #     context: .
  #     args:
  #       requirements: requirements/development.txt
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=djangodocker.settings.development
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - main
  #   depends_on:
  #     - db
  # db:
  #   image: mysql
  #   environment:
  #     MYSQL_DATABASE: djangodocker_db
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - main

# networks: 
#   main: